### PR TITLE
Discovers ISA files as individual files and as Zip file

### PR DESCRIPTION
**Pull request by pcm32**
This PR addresses issue #3 by providing both the individual files (collections for a_ and s_ files) and  all the ISA files in a Zip. The second alternative is provided to keep the file names of the ISA files (Galaxy remanes them when "transforming" them recognized datasets).

### CODE REVIEW

**Comment by pcm32** [comment]
Can @RJMW or someone who has done the conda testing part advise what else is needed for the test to be passed? We don't use conda at our side, but I can confirm that the tool works on Galaxy.

**Comment by Tomnl** [comment]
Have you tried to test with planemo?

I think it is failing because we now have different output files to the original test files 

```
<test>
            <param name="name_of_study" value="test" />
            <param name="inputzip" value="metabolomics_study.zip" />
            <output name="output" value="metabolomics_study/test/index.html" />
</test>
```

I will look into it now

**Comment by Tomnl** [comment]
I have made a few changes and it seems to pass the unit tests now.
- Needed to make sure the inputzip folder is recognized as a zip file by adding: `<param name="inputzip" value="metabolomics_study.zip" ftype="zip" />`
- Added some limited unit testing for the data-collections

Also, I have hidden the old html output file as it had become a bit redundant

**Comment by pcm32** [comment]
Thanks @Tomnl! Besides the testing, is there a real need for the inputzip datatype? I'm under the impression that this was introduced so that Galaxy wouldn't expand a zip file. However when using current versions, when you upload a zip file, if you label it as a zip file, it won't unzip it for you (which I think makes the use of inputzip redundant). This is of course if my understanding of the usage of inputzip is correct.

**Comment by Tomnl** [comment]
Hi @pcm32,

inputzip is just being used as the name of the param the format is actually "zip".

`<param format="zip" name="inputzip" type="data" label="mzML zip file" help="A zipped folder of mzML files"/>`

But you are right that we were using a redundant dependency on the`no_unzip_datatype`.  I have now removed this.

**Pull request merged**
